### ISSUE TITLE
Issues starting the server

### ISSUE THREAD

**Issue by gkirill** [nuzayats/ee8security#1]
Tried running this in docker's OpenJDK 8 but getting the following output and errors, and the application does not respond on localhost:8080

Curl
root@cd21add5e017:/# curl localhost:8080/api/secured/greet
curl: (7) Failed to connect to localhost port 8080: Connection refused

Output when building and running 

root@cd21add5e017:/etc/project# ./mvnw clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< ee8security:ee8security >-----------------------
[INFO] Building ee8security 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ee8security ---
[INFO] Deleting /etc/project/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ee8security ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /etc/project/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ ee8security ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to /etc/project/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ee8security ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /etc/project/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ ee8security ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /etc/project/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ ee8security ---
[INFO] Surefire report directory: /etc/project/target/surefire-reports
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.pom (2.4 kB at 2.8 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.12.4/surefire-providers-2.12.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.12.4/surefire-providers-2.12.4.pom (2.3 kB at 11 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar (37 kB at 89 kB/s)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ee8security.JwtTokenServiceTest
May 10, 2019 6:19:04 AM ee8security.JwtTokenService verifyAndGetSubject
INFO: Token verification failed. The offending token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmb28iLCJleHAiOjE1NTY3MTE5OTl9.92l4ddrw_dhAVmDutgY4W6a2moJGDl1KTKkDzT8XtII"; Reason: JWT expired at 2019-05-01T11:59:59Z. Current time: 2019-05-01T12:00:00Z, a difference of 1000 milliseconds.  Allowed clock skew: 0 milliseconds.
May 10, 2019 6:19:04 AM ee8security.JwtTokenService verifyAndGetSubject
INFO: Token verification failed. The offending token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYXIiLCJleHAiOjE1NTY3MTM4MDB9.3_ByeOWIpZUtTSpH8JTGWG7nMMLrKPa1hEPdfxz9pPg"; Reason: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.426 sec

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-war-plugin:2.2:war (default-war) @ ee8security ---
[INFO] Packaging webapp
[INFO] Assembling webapp [ee8security] in [/etc/project/target/ee8security]
[INFO] Processing war project
[INFO] Copying webapp resources [/etc/project/src/main/webapp]
[INFO] Webapp assembled in [47 msecs]
[INFO] Building war: /etc/project/target/ee8security.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.042 s
[INFO] Finished at: 2019-05-10T06:19:04Z
[INFO] ------------------------------------------------------------------------
root@cd21add5e017:/etc/project# ./mvnw cargo:run -P-useFixedUnixTime
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< ee8security:ee8security >-----------------------
[INFO] Building ee8security 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- cargo-maven2-plugin:1.7.3:run (default-cli) @ ee8security ---
[INFO] [en2.ContainerRunMojo] Resolved container artifact org.codehaus.cargo:cargo-core-container-wildfly:jar:1.7.3 for container wildfly16x
[INFO] [talledLocalContainer] Parsed JBoss version = [16.0.0.Final]
[INFO] [talledLocalContainer] WildFly 16.0.0.Final starting...
[INFO] [neLocalConfiguration] Configuring JBoss using the [standalone] server configuration
[INFO] [talledLocalContainer] 06:19:41,431 INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.0.Final
[INFO] [talledLocalContainer] 06:19:42,153 INFO  [org.jboss.modules] (CLI command executor) JBoss Modules version 1.9.0.Final
[INFO] [talledLocalContainer] 06:19:42,241 INFO  [org.jboss.msc] (CLI command executor) JBoss MSC version 1.4.5.Final
[INFO] [talledLocalContainer] 06:19:42,253 INFO  [org.jboss.threads] (CLI command executor) JBoss Threads version 2.3.3.Final
[INFO] [talledLocalContainer] 06:19:42,425 INFO  [org.jboss.as] (MSC service thread 1-3) WFLYSRV0049: WildFly Full 16.0.0.Final (WildFly Core 8.0.0.Final) starting
[INFO] [talledLocalContainer] 06:19:43,219 INFO  [org.wildfly.security] (ServerService Thread Pool -- 25) ELY00001: WildFly Elytron version 1.8.0.Final
[INFO] [talledLocalContainer] 06:19:43,884 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
[INFO] [talledLocalContainer] 06:19:43,970 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
[INFO] [talledLocalContainer] 06:19:44,152 INFO  [org.jboss.as.patching] (MSC service thread 1-8) WFLYPAT0050: WildFly Full cumulative patch ID is: base, one-off patches include: none
[INFO] [talledLocalContainer] 06:19:44,177 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-5) WFLYDM0111: Keystore /etc/project/target/cargo/configurations/wildfly16x/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
[INFO] [talledLocalContainer] 06:19:44,277 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
[INFO] [talledLocalContainer] 06:19:44,282 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 16.0.0.Final (WildFly Core 8.0.0.Final) started in 2128ms - Started 65 of 79 services (25 services are lazy, passive or on-demand)
[INFO] [talledLocalContainer] 06:19:44,433 INFO  [org.jboss.as.cli.CommandContext] (main) {"outcome" => "success"}
[INFO] [talledLocalContainer] {"outcome" => "success"}
[INFO] [talledLocalContainer] 06:19:44,475 INFO  [org.jboss.as.cli.CommandContext] (main) {"outcome" => "success"}
[INFO] [talledLocalContainer] {"outcome" => "success"}
[INFO] [talledLocalContainer] 06:19:44,498 INFO  [org.jboss.as.cli.CommandContext] (main) {"outcome" => "success"}
[INFO] [talledLocalContainer] {"outcome" => "success"}
[INFO] [talledLocalContainer] 06:19:44,518 INFO  [org.jboss.as.cli.CommandContext] (main) {"outcome" => "success"}
[INFO] [talledLocalContainer] {"outcome" => "success"}
[INFO] [talledLocalContainer] 06:19:44,539 INFO  [org.jboss.as.cli.CommandContext] (main) {"outcome" => "success"}
[INFO] [talledLocalContainer] {"outcome" => "success"}
[INFO] [talledLocalContainer] 06:19:44,574 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0050: WildFly Full 16.0.0.Final (WildFly Core 8.0.0.Final) stopped in 13ms
[INFO] [talledLocalContainer] 06:19:44,580 INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.0.Final
[INFO] [talledLocalContainer] 
[INFO] [stalledLocalDeployer] Deploying [/etc/project/target/ee8security.war] to [/etc/project/target/cargo/configurations/wildfly16x/deployments]...
[INFO] [talledLocalContainer] 06:19:45,019 INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.0.Final
[INFO] [talledLocalContainer] 06:19:45,421 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.5.Final
[INFO] [talledLocalContainer] 06:19:45,432 INFO  [org.jboss.threads] (main) JBoss Threads version 2.3.3.Final
[INFO] [talledLocalContainer] 06:19:45,555 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Full 16.0.0.Final (WildFly Core 8.0.0.Final) starting
[INFO] [talledLocalContainer] 06:19:46,555 INFO  [org.wildfly.security] (ServerService Thread Pool -- 26) ELY00001: WildFly Elytron version 1.8.0.Final
[INFO] [talledLocalContainer] 06:19:47,448 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
[INFO] [talledLocalContainer] 06:19:47,497 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 30) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
[INFO] [talledLocalContainer] 06:19:47,584 INFO  [org.jboss.as.repository] (ServerService Thread Pool -- 35) WFLYDR0001: Content added at location /etc/project/target/cargo/configurations/wildfly16x/data/content/47/7f45bffea5c07b1a3c101d89103d46dea14181/content
[INFO] [talledLocalContainer] 06:19:47,634 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
[INFO] [talledLocalContainer] 06:19:47,656 INFO  [org.xnio] (MSC service thread 1-5) XNIO version 3.6.5.Final
[INFO] [talledLocalContainer] 06:19:47,666 INFO  [org.xnio.nio] (MSC service thread 1-5) XNIO NIO Implementation Version 3.6.5.Final
[INFO] [talledLocalContainer] 06:19:47,741 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 42) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.4)
[INFO] [talledLocalContainer] 06:19:47,787 INFO  [org.wildfly.extension.microprofile.config.smallrye._private] (ServerService Thread Pool -- 58) WFLYCONF0001: Activating WildFly MicroProfile Config Subsystem
[INFO] [talledLocalContainer] 06:19:47,806 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 70) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger for environments running multiple servers. Please make sure the attribute value is unique.
[INFO] [talledLocalContainer] 06:19:47,806 INFO  [org.wildfly.extension.microprofile.opentracing] (ServerService Thread Pool -- 61) WFLYTRACEXT0001: Activating MicroProfile OpenTracing Subsystem
[INFO] [talledLocalContainer] 06:19:47,818 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 62) WFLYNAM0001: Activating Naming Subsystem
[INFO] [talledLocalContainer] 06:19:47,817 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 49) WFLYCLINF0001: Activating Infinispan subsystem.
[INFO] [talledLocalContainer] 06:19:47,826 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 50) WFLYIO001: Worker 'default' has auto-configured to 8 core threads with 64 task threads based on your 4 available processors
[INFO] [talledLocalContainer] 06:19:47,835 INFO  [org.wildfly.extension.microprofile.health.smallrye] (ServerService Thread Pool -- 59) WFLYHEALTH0001: Activating Eclipse MicroProfile Health Subsystem
[INFO] [talledLocalContainer] 06:19:47,846 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 68) WFLYSEC0002: Activating Security Subsystem
[INFO] [talledLocalContainer] 06:19:47,848 INFO  [org.jboss.as.jsf] (ServerService Thread Pool -- 56) WFLYJSF0007: Activated the following JSF Implementations: [main]
[INFO] [talledLocalContainer] 06:19:47,873 INFO  [org.jboss.as.jaxrs] (ServerService Thread Pool -- 51) WFLYRS0016: RESTEasy version 3.6.3.Final
[INFO] [talledLocalContainer] 06:19:47,881 INFO  [org.wildfly.extension.microprofile.metrics.smallrye] (ServerService Thread Pool -- 60) WFLYMETRICS0001: Activating Eclipse MicroProfile Metrics Subsystem
[INFO] [talledLocalContainer] 06:19:47,889 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-8) WFLYMAIL0002: Unbound mail session [java:jboss/mail/Default]
[INFO] [talledLocalContainer] 06:19:47,919 INFO  [org.jboss.as.security] (MSC service thread 1-8) WFLYSEC0001: Current PicketBox version=5.0.3.Final
[INFO] [talledLocalContainer] 06:19:47,926 INFO  [org.jboss.as.connector] (MSC service thread 1-6) WFLYJCA0009: Starting JCA Subsystem (WildFly/IronJacamar 1.4.12.Final)
[INFO] [talledLocalContainer] 06:19:47,949 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-4) WFLYJCA0018: Started Driver service with driver-name = h2
[INFO] [talledLocalContainer] 06:19:47,962 INFO  [org.jboss.as.webservices] (ServerService Thread Pool -- 72) WFLYWS0002: Activating WebServices Extension
[INFO] [talledLocalContainer] 06:19:47,990 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
[INFO] [talledLocalContainer] 06:19:47,994 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0003: Undertow 2.0.19.Final starting
[INFO] [talledLocalContainer] 06:19:48,018 INFO  [org.jboss.remoting] (MSC service thread 1-5) JBoss Remoting version 5.0.8.Final
[INFO] [talledLocalContainer] 06:19:48,024 INFO  [io.smallrye.metrics] (MSC service thread 1-7) Converted [2] config entries and added [4] replacements
[INFO] [talledLocalContainer] 06:19:48,027 INFO  [io.smallrye.metrics] (MSC service thread 1-7) Converted [3] config entries and added [14] replacements
[INFO] [talledLocalContainer] 06:19:48,033 INFO  [org.jboss.as.naming] (MSC service thread 1-4) WFLYNAM0003: Starting Naming Service
[INFO] [talledLocalContainer] 06:19:48,033 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-4) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
[INFO] [talledLocalContainer] 06:19:48,263 INFO  [org.jboss.as.ejb3] (MSC service thread 1-5) WFLYEJB0482: Strict pool mdb-strict-max-pool is using a max instance size of 16 (per class), which is derived from the number of CPUs on this host.
[INFO] [talledLocalContainer] 06:19:48,265 INFO  [org.jboss.as.ejb3] (MSC service thread 1-4) WFLYEJB0481: Strict pool slsb-strict-max-pool is using a max instance size of 64 (per class), which is derived from thread worker pool sizing.
[INFO] [talledLocalContainer] 06:19:48,295 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 71) WFLYUT0014: Creating file handler for path '/etc/project/target/cargo/installs/wildfly-16.0.0.Final/wildfly-16.0.0.Final/welcome-content' with options [directory-listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
[INFO] [talledLocalContainer] 06:19:48,315 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0012: Started server default-server.
[INFO] [talledLocalContainer] 06:19:48,317 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0018: Host default-host starting
[INFO] [talledLocalContainer] 06:19:48,509 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service org.wildfly.undertow.listener.default: org.jboss.msc.service.StartException in service org.wildfly.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:211)
[INFO] [talledLocalContainer] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1738)
[INFO] [talledLocalContainer] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1700)
[INFO] [talledLocalContainer] 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1558)
[INFO] [talledLocalContainer] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[INFO] [talledLocalContainer] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
[INFO] [talledLocalContainer] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
[INFO] [talledLocalContainer] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
[INFO] [talledLocalContainer] 	at java.lang.Thread.run(Thread.java:748)
[INFO] [talledLocalContainer] Caused by: java.net.SocketException: Protocol family unavailable
[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind0(Native Method)
[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind(Net.java:433)
[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind(Net.java:425)
[INFO] [talledLocalContainer] 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[INFO] [talledLocalContainer] 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[INFO] [talledLocalContainer] 	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:178)
[INFO] [talledLocalContainer] 	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:303)
[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:106)
[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:199)
[INFO] [talledLocalContainer] 	... 8 more
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] 06:19:48,694 INFO  [org.jboss.as.ejb3] (MSC service thread 1-4) WFLYEJB0493: EJB subsystem suspension complete
[INFO] [talledLocalContainer] 06:19:48,780 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
[INFO] [talledLocalContainer] 06:19:49,133 INFO  [org.jboss.as.patching] (MSC service thread 1-3) WFLYPAT0050: WildFly Full cumulative patch ID is: base, one-off patches include: none
[INFO] [talledLocalContainer] 06:19:49,175 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-4) WFLYDM0111: Keystore /etc/project/target/cargo/configurations/wildfly16x/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
[INFO] [talledLocalContainer] 06:19:49,213 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-8) WFLYDS0013: Started FileSystemDeploymentService for directory /etc/project/target/cargo/configurations/wildfly16x/deployments
[INFO] [talledLocalContainer] 06:19:49,231 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0027: Starting deployment of "ee8security.war" (runtime-name: "ee8security.war")
[INFO] [talledLocalContainer] 06:19:49,266 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service org.wildfly.undertow.listener.https: org.jboss.msc.service.StartException in service org.wildfly.undertow.listener.https: WFLYUT0082: Could not start 'https' listener.
[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:211)
[INFO] [talledLocalContainer] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1738)
[INFO] [talledLocalContainer] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1700)
[INFO] [talledLocalContainer] 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1558)
[INFO] [talledLocalContainer] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[INFO] [talledLocalContainer] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
[INFO] [talledLocalContainer] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
[INFO] [talledLocalContainer] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
[INFO] [talledLocalContainer] 	at java.lang.Thread.run(Thread.java:748)
[INFO] [talledLocalContainer] Caused by: java.net.SocketException: Protocol family unavailable
[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind0(Native Method)
[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind(Net.java:433)
[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind(Net.java:425)
[INFO] [talledLocalContainer] 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[INFO] [talledLocalContainer] 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[INFO] [talledLocalContainer] 	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:178)
[INFO] [talledLocalContainer] 	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:303)
[INFO] [talledLocalContainer] 	at io.undertow.protocols.ssl.UndertowXnioSsl.createSslConnectionServer(UndertowXnioSsl.java:357)
[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.HttpsListenerService.startListening(HttpsListenerService.java:143)
[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:199)
[INFO] [talledLocalContainer] 	... 8 more
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] 06:19:49,565 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
[INFO] [talledLocalContainer]     ("subsystem" => "undertow"),
[INFO] [talledLocalContainer]     ("server" => "default-server"),
[INFO] [talledLocalContainer]     ("http-listener" => "default")
[INFO] [talledLocalContainer] ]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.undertow.listener.default" => "WFLYUT0082: Could not start 'default' listener.
[INFO] [talledLocalContainer]     Caused by: java.net.SocketException: Protocol family unavailable"}}
[INFO] [talledLocalContainer] 06:19:49,584 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
[INFO] [talledLocalContainer]     ("subsystem" => "undertow"),
[INFO] [talledLocalContainer]     ("server" => "default-server"),
[INFO] [talledLocalContainer]     ("https-listener" => "https")
[INFO] [talledLocalContainer] ]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.undertow.listener.https" => "WFLYUT0082: Could not start 'https' listener.
[INFO] [talledLocalContainer]     Caused by: java.net.SocketException: Protocol family unavailable"}}
[INFO] [talledLocalContainer] 06:19:49,633 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 43) WFLYSRV0010: Deployed "ee8security.war" (runtime-name : "ee8security.war")
[INFO] [talledLocalContainer] 06:19:49,637 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
[INFO] [talledLocalContainer] WFLYCTL0186:   Services which failed to start:      service org.wildfly.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
[INFO] [talledLocalContainer]       service org.wildfly.undertow.listener.https: WFLYUT0082: Could not start 'https' listener.
[INFO] [talledLocalContainer] WFLYCTL0448: 2 additional services are down due to their dependencies being missing or failed
[INFO] [talledLocalContainer] 06:19:49,716 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
[INFO] [talledLocalContainer] 06:19:49,725 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
[INFO] [talledLocalContainer] 06:19:49,726 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
[INFO] [talledLocalContainer] 06:19:49,727 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 16.0.0.Final (WildFly Core 8.0.0.Final) started (with errors) in 5041ms - Started 299 of 532 services (4 services failed or missing dependencies, 324 services are lazy, passive or on-demand)
[INFO] [talledLocalContainer] 06:19:50,149 INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.0.Final
[INFO] [talledLocalContainer] 06:19:50,792 INFO  [org.xnio] (CLI command executor) XNIO version 3.6.5.Final
[INFO] [talledLocalContainer] 06:19:50,803 INFO  [org.xnio.nio] (CLI command executor) XNIO NIO Implementation Version 3.6.5.Final
[INFO] [talledLocalContainer] 06:19:50,818 INFO  [org.jboss.remoting] (CLI command executor) JBoss Remoting version 5.0.8.Final
[INFO] [talledLocalContainer] 06:19:50,839 INFO  [org.jboss.threads] (CLI command executor) JBoss Threads version 2.3.3.Final
[INFO] [talledLocalContainer] 06:19:50,909 INFO  [org.wildfly.security] (CLI command executor) ELY00001: WildFly Elytron version 1.8.0.Final
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] WildFly 16.0.0.Final started on port [8080]
[INFO] Press Ctrl-C to stop the container...

**Comment by nuzayats** [comment]
@gkirill Hello, could you please try this instead?

```
_JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true" ./mvnw cargo:run -P-useFixedUnixTime
```

It seems that WildFly has some issue with running on Docker. A similar issue and some workarounds are reported here https://github.com/jboss-dockerfiles/jbpm/issues/15#issuecomment-356337391

**Comment by gkirill** [comment]
Hm, still could not run with this inside a container. So I just ran it in a conventional way. Thanks for the answer anyway!
